### ISSUE TITLE
link to docs is broken

### ISSUE THREAD

**Issue by eahenle** [JuliaGraphs/MetaGraphs.jl#3]
The GitHub Pages link to the documentation returns a 404 error.

**Comment by ViralBShah** [comment]
The gh-pages branch is not getting pushed.

**Comment by ViralBShah** [comment]
cc @matbesancon

**Comment by ViralBShah** [comment]
There's a problem with deployment of docs.

https://github.com/JuliaGraphs/MetaGraphs.jl/runs/4043901917?check_suite_focus=true#step:6:31

**Comment by CarloLucibello** [comment]
@matbesancon doesn't seem to be fixed by #7

**Comment by ViralBShah** [comment]
I set up Github Pages. Works now: https://juliagraphs.org/MetaGraphs.jl/dev/
