### ISSUE TITLE
LightGraphs is not compatible anymore

### ISSUE THREAD

**Issue by Codsilla** [JuliaGraphs/MetaGraphs.jl#34]
MetaGraphs was working with LightGraphs.jl before but this isn't the case anymore.

```julia
julia> using LightGraphs, MetaGraphs
julia> g = DiGraph(5)
julia> G = MetaDiGraph(g)
ERROR: MethodError: no method matching Graphs.SimpleGraphs.SimpleDiGraph(::SimpleDiGraph{Int64})
Closest candidates are:
  Graphs.SimpleGraphs.SimpleDiGraph() ...
```

**Comment by simonschoelly** [comment]
The code of LightGraphs.jl has moved to [Graphs.jl](https://github.com/JuliaGraphs/Graphs.jl), and the current versions of MetaGraphs also depend on Graphs.jl. You can just import Graphs instead of LightGraphs and everything should work as before.

**Comment by Codsilla** [comment]
Thank you for your quick and clear reply!
