### ISSUE TITLE
JLD2 compat

### ISSUE THREAD

**Issue by elbert5770** [JuliaGraphs/MetaGraphs.jl#45]
⌅ [033835bb] JLD2 v0.4.53
⌅ [033835bb] JLD2 v0.4.53 (<v0.5.7): MetaGraphs

**Comment by gdalle** [comment]
You should update to the latest version of MetaGraphs, that will fix it

**Comment by elbert5770** [comment]
Great thank you.  It seems that Images → ImageSegmentation is holding back MetaGraphs.

**Comment by gdalle** [comment]
Alright then, I'm gonna close the issue here and let you open one in the image ecosystem 😊
